version: '3.8'

services:
  postgres:
    image: postgres:alpine3.22
    container_name: news_feeder_db
    environment:
      POSTGRES_DB: news_feeder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news_feeder_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  news_feeder_network:
    driver: bridge